// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hcaociwrmgxabcvtlgbj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhjYW9jaXdybWd4YWJjdnRsZ2JqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2NTk5MjEsImV4cCI6MjA2NDIzNTkyMX0.CSb1yceW6ZNgciCosoGtA5VD7Yd6wgFsHXSxzAs20Xs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);